#include "myPriorityQueue.h"
#include <assert.h>

// The priority queue is a data structure used when elements need to be released based on priority.
// Priority can be assigned based off of various factors depending on what the queue is holding.

void swap(queueElement *a, queueElement *b){
    queueElement temp = *a;
    *a = *b;
    *b = temp;
}

void init(myPriorityQueue *pqueue, int highPriorityDequeuedFirst){
    pqueue->count = 0;
    pqueue->highPriorityDequeuedFirst = highPriorityDequeuedFirst;
}

bool isEmpty(myPriorityQueue *pqueue){
    // Time Complexity: O(1)
    if (pqueue->count == 0){
        return true;
    }
    return false;

}

bool isFull(myPriorityQueue *pqueue){
    // Time Complexity: O(1)
    if (pqueue->count == MAX_SIZE){
        return true;
    }
    return false;
}

void heapUp(myPriorityQueue *pqueue, int index){
    // Time Complexity: O(log(n))

    if (index==0) {return;}

    int direction = pqueue->highPriorityDequeuedFirst ? 1: -1;

    if (direction*pqueue->arr[(index-1)/2].priority < direction*pqueue->arr[index].priority){
        swap(&pqueue->arr[(index-1)/2], &pqueue->arr[index]);
        heapUp(pqueue, (index-1)/2);
    }

}

void heapDown(myPriorityQueue *pqueue, int index){
    // Time Complexity: O(log(n))

    int direction = pqueue->highPriorityDequeuedFirst ? 1: -1;

    int greatestOrLowest = index;
    int leftIndex = (2*index)+1;
    int rightIndex = (2*index)+2;

    if (leftIndex < pqueue->count && direction*pqueue->arr[leftIndex].priority > direction*pqueue->arr[greatestOrLowest].priority)
        greatestOrLowest = leftIndex;

    if (rightIndex < pqueue->count && direction*pqueue->arr[rightIndex].priority > direction*pqueue->arr[greatestOrLowest].priority)
        greatestOrLowest = rightIndex;

    if (greatestOrLowest != index) {
        swap(&pqueue->arr[index], &pqueue->arr[greatestOrLowest]);
        heapDown(pqueue, greatestOrLowest);
    }

}

void enqueue(myPriorityQueue *pqueue, queueElement element){
    // Time Complexity: O(log(n))
    if (isFull(pqueue)){
        printf("(%d,%d) could not be queued. The queue is full!\n", element.val, element.priority);
        return;
    }

    pqueue->arr[pqueue->count++] = element;
    heapUp(pqueue, pqueue->count - 1);

}

queueElement dequeue(myPriorityQueue *pqueue){
    // Time Complexity: O(log(n))
    if (isEmpty(pqueue)){
        printf("Nothing to be dequeued!\n");
        queueElement element = {-1, -10000};
        return element;
    }

    queueElement element = pqueue->arr[0];
    pqueue->arr[0] = pqueue->arr[--pqueue->count];
    heapDown(pqueue, 0);
    return element;

}

void peek(myPriorityQueue *pqueue){
    // Time Complexity: O(1)
    if (isEmpty(pqueue)){
        printf("The queue is empty. Nothing to see here!\n");
        return;
    }

    queueElement topElement = pqueue->arr[0];
    printf("(%d, %d) is at the front of the queue\n", topElement.val, topElement.priority);
    return;
} 

#ifdef MYPRIORITYQUEUE_TEST
int main(){

    // The following test code is generated by Claude AI and verified that it covers the necessary
    // cases by Hassan Shafeeq
        myPriorityQueue pq;
    init(&pq, 1); // highPriorityDequeuedFirst = 1 -> max-heap behaviour
 
    // Empty queue checks
    assert(isEmpty(&pq) == true);
    assert(isFull(&pq) == false);
 
    // Enqueue out of priority order, expect max-heap to sort it out
    queueElement items[] = {
        {10, 5}, {20, 1}, {30, 9}, {40, 3}, {50, 7}
    };
    for (int i = 0; i < 5; i++){
        enqueue(&pq, items[i]);
    }
    assert(pq.count == 5);
 
    // Highest priority should now be at the root
    peek(&pq); // expect (30, 9)
 
    // Dequeue should come out in descending priority order
    int expectedPriorities[] = {9, 7, 5, 3, 1};
    for (int i = 0; i < 5; i++){
        queueElement e = dequeue(&pq);
        printf("e.priority = {%d}\n", e.priority);
        assert(e.priority == expectedPriorities[i]);
    }
    assert(isEmpty(&pq) == true);
 
    // Duplicate priorities — heap doesn't guarantee FIFO/stability,
    // just confirm both come out before anything lower
    enqueue(&pq, (queueElement){1, 5});
    enqueue(&pq, (queueElement){2, 5});
    enqueue(&pq, (queueElement){3, 1});
    queueElement a = dequeue(&pq);
    queueElement b = dequeue(&pq);
    assert(a.priority == 5 && b.priority == 5);
 
    // Fill to MAX_SIZE and confirm isFull, then confirm overflow is rejected
    init(&pq, 1);
    for (int i = 0; i < MAX_SIZE; i++){
        enqueue(&pq, (queueElement){i, i});
    }
    assert(isFull(&pq) == true);
    enqueue(&pq, (queueElement){999, 999}); // should print rejection, count unchanged
    assert(pq.count == MAX_SIZE);
 
    printf("All max-priority-first tests passed!\n");
 
    // ------------------------------------------------------------------
    // Min-heap mode: highPriorityDequeuedFirst = 0 -> lowest priority first
    // ------------------------------------------------------------------
    myPriorityQueue minpq;
    init(&minpq, 0);
 
    assert(isEmpty(&minpq) == true);
    assert(isFull(&minpq) == false);
 
    queueElement minItems[] = {
        {10, 5}, {20, 1}, {30, 9}, {40, 3}, {50, 7}
    };
    for (int i = 0; i < 5; i++){
        enqueue(&minpq, minItems[i]);
    }
    assert(minpq.count == 5);
 
    // Lowest priority should now be at the root
    peek(&minpq); // expect (20, 1)
 
    // Dequeue should come out in ascending priority order
    int expectedMinPriorities[] = {1, 3, 5, 7, 9};
    for (int i = 0; i < 5; i++){
        queueElement e = dequeue(&minpq);
        printf("e.priority = {%d}\n", e.priority);
        assert(e.priority == expectedMinPriorities[i]);
    }
    assert(isEmpty(&minpq) == true);
 
    // Duplicate priorities in min-heap mode — confirm both lowest-tied
    // elements come out before anything higher
    enqueue(&minpq, (queueElement){1, 5});
    enqueue(&minpq, (queueElement){2, 5});
    enqueue(&minpq, (queueElement){3, 9});
    queueElement c = dequeue(&minpq);
    queueElement d = dequeue(&minpq);
    assert(c.priority == 5 && d.priority == 5);
 
    // Interleaved enqueue/dequeue on a min-heap to exercise heapDown
    // with a changing tree shape
    init(&minpq, 0);
    enqueue(&minpq, (queueElement){1, 8});
    enqueue(&minpq, (queueElement){2, 4});
    enqueue(&minpq, (queueElement){3, 6});
    assert(dequeue(&minpq).priority == 4);
    enqueue(&minpq, (queueElement){4, 2});
    enqueue(&minpq, (queueElement){5, 10});
    assert(dequeue(&minpq).priority == 2);
    assert(dequeue(&minpq).priority == 6);
    assert(dequeue(&minpq).priority == 8);
    assert(dequeue(&minpq).priority == 10);
    assert(isEmpty(&minpq) == true);
 
    // Fill to MAX_SIZE in min-heap mode and confirm overflow is rejected
    init(&minpq, 0);
    for (int i = 0; i < MAX_SIZE; i++){
        enqueue(&minpq, (queueElement){i, i});
    }
    assert(isFull(&minpq) == true);
    enqueue(&minpq, (queueElement){999, 999}); // should print rejection, count unchanged
    assert(minpq.count == MAX_SIZE);
    assert(dequeue(&minpq).priority == 0); // lowest priority still comes out first
 
    printf("All min-priority-first tests passed!\n");
 
    return 0;
}
#endif