#include "myPriorityQueue.h"
#include <assert.h>

// The priority queue is a data structure used when elements need to be released based on priority.
// Priority can be assigned based off of various factors depending on what the queue is holding.

void swap(queueElement *a, queueElement *b){
    queueElement temp = *a;
    *a = *b;
    *b = temp;
}

void init(myPriorityQueue *pqueue){
    pqueue->count = 0;
}

bool isEmpty(myPriorityQueue *pqueue){
    // Time Complexity: O(1)
    if (pqueue->count == 0){
        return true;
    }
    return false;

}

bool isFull(myPriorityQueue *pqueue){
    // Time Complexity: O(1)
    if (pqueue->count == MAX_SIZE){
        return true;
    }
    return false;
}

void heapUp(myPriorityQueue *pqueue, int index){
    // Time Complexity: O(log(n))
    if (pqueue->arr[(index-1)/2].priority < pqueue->arr[index].priority){
        swap(&pqueue->arr[(index-1)/2], &pqueue->arr[index]);
        heapUp(pqueue, (index-1)/2);
    }

}

void heapDown(myPriorityQueue *pqueue, int index){
    // Time Complexity: O(log(n))
    int greatest = index;
    int leftIndex = (2*index)+1;
    int rightIndex = (2*index)+2;

    if (leftIndex < pqueue->count && pqueue->arr[leftIndex].priority > pqueue->arr[greatest].priority)
        greatest = leftIndex;

    if (rightIndex < pqueue->count && pqueue->arr[rightIndex].priority > pqueue->arr[greatest].priority)
        greatest = rightIndex;

    if (greatest != index) {
        swap(&pqueue->arr[index], &pqueue->arr[greatest]);
        heapDown(pqueue, greatest);
    }

}

void enqueue(myPriorityQueue *pqueue, queueElement element){
    // Time Complexity: O(log(n))
    if (isFull(pqueue)){
        printf("(%d,%d) could not be queued. The queue is full!\n", element.val, element.priority);
        return;
    }

    pqueue->arr[pqueue->count++] = element;
    heapUp(pqueue, pqueue->count - 1);

}

queueElement dequeue(myPriorityQueue *pqueue){
    // Time Complexity: O(log(n))
    if (isEmpty(pqueue)){
        printf("Nothing to be dequeued!\n");
        queueElement element = {-1, INT_MIN};
        return element;
    }

    queueElement element = pqueue->arr[0];
    pqueue->arr[0] = pqueue->arr[--pqueue->count];
    heapDown(pqueue, 0);
    return element;

}

void peek(myPriorityQueue *pqueue){
    // Time Complexity: O(1)
    if (isEmpty(pqueue)){
        printf("The queue is empty. Nothing to see here!\n");
        return;
    }

    queueElement topElement = pqueue->arr[0];
    printf("(%d, %d) is at the front of the queue\n", topElement.val, topElement.priority);
    return;
} 

int main(){

    // The following test code is generated by Claude AI and verified that it covers the necessary
    // cases by Hassan Shafeeq
    myPriorityQueue pq;
    init(&pq);

    // Empty queue checks
    assert(isEmpty(&pq) == true);
    assert(isFull(&pq) == false);

    // Enqueue out of priority order, expect max-heap to sort it out
    queueElement items[] = {
        {10, 5}, {20, 1}, {30, 9}, {40, 3}, {50, 7}
    };
    for (int i = 0; i < 5; i++){
        enqueue(&pq, items[i]);
    }
    assert(pq.count == 5);

    // Highest priority should now be at the root
    peek(&pq); // expect (30, 9)

    // Dequeue should come out in descending priority order
    int expectedPriorities[] = {9, 7, 5, 3, 1};
    for (int i = 0; i < 5; i++){
        queueElement e = dequeue(&pq);
        printf("e.priority = {%d}\n", e.priority);
        assert(e.priority == expectedPriorities[i]);
    }
    assert(isEmpty(&pq) == true);

    // Duplicate priorities — heap doesn't guarantee FIFO/stability,
    // just confirm both come out before anything lower
    enqueue(&pq, (queueElement){1, 5});
    enqueue(&pq, (queueElement){2, 5});
    enqueue(&pq, (queueElement){3, 1});
    queueElement a = dequeue(&pq);
    queueElement b = dequeue(&pq);
    assert(a.priority == 5 && b.priority == 5);

    // Fill to MAX_SIZE and confirm isFull, then confirm overflow is rejected
    init(&pq);
    for (int i = 0; i < MAX_SIZE; i++){
        enqueue(&pq, (queueElement){i, i});
    }
    assert(isFull(&pq) == true);
    enqueue(&pq, (queueElement){999, 999}); // should print rejection, count unchanged
    assert(pq.count == MAX_SIZE);

    printf("All priority queue tests passed!\n");

    return 0;
}